# Generated by Django 5.2.5 on 2025-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_loanapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='nida_picture',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='nida_back',
            field=models.ImageField(blank=True, null=True, upload_to='loan_documents/nida_pictures/back/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='nida_front',
            field=models.ImageField(blank=True, null=True, upload_to='loan_documents/nida_pictures/front/'),
        ),
    ]
