# Generated by Django 5.2.5 on 2025-08-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
