# Generated by Django 5.2.5 on 2025-08-12 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_notification_receiver_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='loan_documents/receipts/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='myapp.loanapplication')),
            ],
        ),
    ]
