# Generated by Django 5.2.5 on 2025-08-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_loanreceipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanreceipt',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
