# Generated by Django 5.2.5 on 2025-08-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_phone_number_loanreceipt_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanreceipt',
            old_name='receipt_image',
            new_name='receipt',
        ),
        migrations.RemoveField(
            model_name='loanreceipt',
            name='loan_application',
        ),
    ]
