# Generated by Django 5.2.5 on 2025-08-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_receipt_image_loanreceipt_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanreceipt',
            old_name='receipt',
            new_name='receipt_image',
        ),
    ]
